version: "3.7"
services:
  gitlab:
    image: gitlab/gitlab-ce:${gitlab_ce_tag:-13.3.5-ce.0}
    container_name: gitlab
    restart: always
    hostname: 'gitlab'
    domainname: gitlab.example.com
    ports:
     - "80:80"
     - "2443:2443"
     - "2022:22"
     # - "4567:4567"
     - "5050:5050"
    volumes:
     - "${GITLAB_HOME:-./GITLAB_HOME}/data:/var/opt/gitlab"
     - "${GITLAB_HOME:-./GITLAB_HOME}/logs:/var/log/gitlab"
     - "${GITLAB_HOME:-./GITLAB_HOME}/config:/etc/gitlab"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    # network_mode: bridge
  gitlab-runner:
    # image: gitlab/gitlab-runner:latest
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
     - "./gitlab-runner/config:/etc/gitlab-runner"
     - "/var/run/docker.sock:/var/run/docker.sock"
    # networks:
    #  mynet:
    #   ipv4_address: 172.20.0.3
    depends_on:
      - gitlab
